### PR TITLE
fix(docker): update location for entrypoint.sh

### LINKED ISSUE #723: Charts[Root Container]: Update location for entrypoint.sh to align with production settings
Currently `entrypoint.sh` is placed under `/etc/network-node` directory, which is not where it exists in production setting. In order to align the setup with production environment, we need to put it under `/opt/hgcapp/services-hedera/HapiApp2.0`.

This however requires updating the charts so that it does not mount an empty directory at `/opt/hgcapp` and overwrites the entrypoint.sh file.
```[tasklist]
### Tasks
- [ ] https://github.com/hashgraph/full-stack-testing/issues/745
```

### PR DESCRIPTION
**Pull request by leninmehedy**
## Description

This pull request changes the following:

- update Dockerfile for `ubi8-init-java17` and `ubi8-init-java21` images to put entrypoint.sh in `/opt/hgcapp/services-hedera/HapiApp2.0/`
- do not reset the directory `/opt/hgcapp/services-hedera/HapiApp2.0/` during node setup anymore (as otherwise it would delete the entrypoint.sh)
- update `setupHapiDirectories` function with correct list of paths as required for e2e tests

### Related Issues

- Closes #723 
- Depends on #753

### CODE REVIEW

File: solo/src/core/platform_installer.mjs [hunk 1]
```diff
@@ -35,20 +35,32 @@ export class PlatformInstaller {
     this.k8 = k8
   }
 
+  /**
+   * Setup directories
+   * @param podName
+   * @param containerName
+   * @return {Promise<boolean>}
+   */
   async setupHapiDirectories (podName, containerName = constants.ROOT_CONTAINER) {
```
Comment (leninmehedy) [inline solo/src/core/platform_installer.mjs:44]: This function `setupHapiDirectories` is only used during tests currently.

**Review by jeromy-cannon — APPROVED** [review]
