### PR TITLE
fix(cli): solo init should reset cached config

### LINKED ISSUE #734: CLI[BUG]: fst-chart-version of 0.19.1 was pulled from cache instead of using 0.20.0 from package.json
not sure if we want to keep it this way as the helm charts, docker containers, and solo will diverge on versions in the future.  But, I have to manually delete the ~/.solo directory, and also, I don't think there is an option to reset the cache without manually deleting it.

### PR DESCRIPTION
**Pull request by leninmehedy**
## Description

This pull request changes the following:

- solo init should reset cached config

### Related Issues

- Closes #734

### CODE REVIEW

**Review by jeromy-cannon — APPROVED** [review]

File: solo/src/commands/cluster.mjs [hunk 1]
```diff
@@ -189,9 +189,11 @@ export class ClusterCommand extends BaseCommand {
       {
         title: `Uninstall '${constants.FULLSTACK_CLUSTER_SETUP_CHART}' chart`,
         task: async (ctx, _) => {
-          const namespace = ctx.config.clusterSetupNamespace
+          const namespace = ctx.config.namespace
```
Comment (jeromy-cannon) [inline solo/src/commands/cluster.mjs:192]:
```suggestion
          const namespace = ctx.config.clusterSetupNamespace
```
