### PR TITLE
fix: use correct variable name to check platform version

### LINKED ISSUE #502: Chart[Node] Script fails to create config.txt for v0.42.5

### PR DESCRIPTION
**Pull request by leninmehedy**
## Description

This pull request changes the following:

- fix variable name to check platform version

### Related Issues

- Closes #502

### CODE REVIEW

**Review by jeromy-cannon — APPROVED** [review]

File: dev/scripts/helper.sh [hunk 1]
```diff
@@ -355,7 +358,9 @@ function prep_address_book() {
   done
 
   # for v.41.* onward
-  #  config_lines+=("nextNodeId, ${node_seq}")
+  if [[ "${PLATFORM_VERSION}" == v0.41* ]]; then
```
Comment (leninmehedy) [inline dev/scripts/helper.sh:361]: Need to fix this check by extracting the MINOR version and checking it is greater than 40

Comment (leninmehedy) [reply dev/scripts/helper.sh]: fixed
